# Generated by Django 4.2.7 on 2023-11-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soft',
            options={'verbose_name': 'Програма', 'verbose_name_plural': 'Програми'},
        ),
    ]
